# Generated by Django 5.0.4 on 2024-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.CharField(choices=[('0', '0%'), ('5', '5%'), ('10', '10%')], default='10', max_length=10),
        ),
    ]
