# Generated by Django 5.0.4 on 2024-07-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(default='Paraguay', max_length=100),
            preserve_default=False,
        ),
    ]
