# Generated by Django 5.0.4 on 2024-04-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoNumeroFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='numeracion',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total_exentas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total_iva_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total_iva_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='iva_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='iva_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='iva_exenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='establecimiento',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='punto_expedicion',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
