# Generated by Django 5.0.4 on 2024-04-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_ultimonumerofactura_factura_numeracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='sub_total_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='sub_total_iva_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='sub_total_iva_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
