# Generated by Django 5.0.4 on 2024-04-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_remove_itemfactura_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfactura',
            name='iva',
        ),
    ]
