# Generated by Django 5.0.4 on 2024-04-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_remove_itemfactura_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total_exentas',
        ),
    ]
