# Generated by Django 5.0.4 on 2024-04-30 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_activo'),
        ('factura', '0006_remove_factura_total_exentas'),
        ('producto', '0003_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
    ]
