# Generated by Django 4.2.11 on 2024-07-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_alter_factura_cliente_alter_itemfactura_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
