# Generated by Django 5.0.4 on 2024-07-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0009_factura_proveedor_alter_factura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='operacion',
            field=models.CharField(blank=True, choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=100, null=True),
        ),
    ]
